README.md
Commits squashed to fix first omission of signed-off-by.
From first commit:
- Installing/running/very first steps still incomplete
- reorganized a bit
- simplified language a bit
- tried not to remove Alex's voice completely (it's compelling)
- Signed-off-by: Jennifer Rondeau (jrondeau@heptio.com)
=> first pass readme edits

ksonnet.beta.1/k.libsonnet, ksonnet.beta.1/util.libsonnet
Also move app.v1.container enhancements to be core.v1.container instead.
Signed-off-by: Joe Beda <joe.github@bedafamily.com>
=> Add util package with a prune function.

README.md
Signed-off-by: JENNIFER RONDEAU <jrondeau@heptio.com>
isue #11
=> remove broken example link

README.md, examples/readme/hello-nginx.jsonnet
Also, recommend use of `jsonnet -J` rather than hardcoding relative
paths to ksonnet-lib root.
=> Update front-page example to actually work

README.md, docs/TUTORIAL.md, examples/readme/hello-nginx.jsonnet
DO NOT MERGE. INCOMPLETE, ADDING PR FOR EARLY COMMENTS
=> beta 2 tutorial

docs/TUTORIAL.md
=> Minor typo

docs/TUTORIAL.md
"ElasticSearch" -> "Elasticsearch"
=> Fixed casing of Elasticsearch

docs/TUTORIAL.md
"VisualStudio" -> "Visual Studio"
=> Typo in product name

ksonnet-gen/ksonnet/emit.go, ksonnet-gen/kubeversion/data.go, ksonnet-gen/kubeversion/version.go, ksonnet-gen/main.go
Signed-off-by: Alex Clemmer <clemmer.alexander@gmail.com>
=> Generate `k.libsonnet` automatically

ksonnet-gen/README.md
=> [trivial] Fix typo in ksonnet-gen/README

.gitignore, ksonnet-gen/nodemaker/nodemaker.go, ksonnet-gen/nodemaker/nodemaker_test.go
nodemaker provides a facility to generate jsonnet AST objects.
=> Add node builder

ksonnet-gen/ksonnet/catalog.go, ksonnet-gen/ksonnet/catalog_test.go, ksonnet-gen/ksonnet/component.go, ksonnet-gen/ksonnet/component_test.go, ksonnet-gen/ksonnet/description.go, ksonnet-gen/ksonnet/description_test.go, ksonnet-gen/ksonnet/object_test.go, ksonnet-gen/ksonnet/properties.go, ksonnet-gen/ksonnet/properties_test.go, ksonnet-gen/ksonnet/resource_test.go, ksonnet-gen/ksonnet/strings.go, ksonnet-gen/ksonnet/strings_test.go, ksonnet-gen/ksonnet/testdata/deployment.json, ksonnet-gen/ksonnet/testdata/invalid_ref.json, ksonnet-gen/ksonnet/type_test.go, ksonnet-gen/kubespec/importer.go
The definition catalog maintains a dictionary of definitions specified
in a swagger file. The catalog provides functions to retrieve lists of
types and fields.
=> Create definition catalog

ksonnet-gen/ksonnet/catalog.go, ksonnet-gen/ksonnet/catalog_test.go, ksonnet-gen/ksonnet/testdata/deployment.json, ksonnet-gen/ksonnet/testdata/invalid_definition.json, ksonnet-gen/ksonnet/testdata/invalid_ref.json
=> check for k8s version when creating catalog

ksonnet-gen/ksonnet/catalog.go, ksonnet-gen/ksonnet/catalog_test.go, ksonnet-gen/ksonnet/component_test.go, ksonnet-gen/ksonnet/document.go, ksonnet-gen/ksonnet/document_integration_test.go, ksonnet-gen/ksonnet/ksonnet.go, ksonnet-gen/kubespec/importer.go, ksonnet-gen/kubespec/importer_test.go, ksonnet-gen/kubespec/parsing.go
* returns the version of the ksonnet-lib
* adds a schema checksum to the generate k8s.libsonnet
=> Return ksonnet-lib version

ksonnet-gen/ksonnet/document_integration_test.go, ksonnet-gen/ksonnet/extension.go, ksonnet-gen/ksonnet/testdata/generated_k.libsonnet
=> fixes bug in call to setInter

ksonnet-gen/astext/astext.go, ksonnet-gen/astext/astext_test.go
Add helper to create ast object fields. Will create a field with the proper identifier.
=> adding ast field creator

ksonnet-gen/ksonnet/custom_constructor.go
=> add data parameter to configMap

ksonnet-gen/printer/printer.go, ksonnet-gen/printer/printer_test.go, ksonnet-gen/printer/testdata/object_comp
=> Add rudimentary support for object comprehensions

ksonnet-gen/nodemaker/nodemaker.go
=> expose convert value to node

ksonnet-gen/printer/printer.go, ksonnet-gen/printer/printer_test.go, ksonnet-gen/printer/testdata/importstr
=> Print importstr

ksonnet-gen/printer/printer.go, ksonnet-gen/printer/printer_test.go, ksonnet-gen/printer/testdata/array_comp, ksonnet-gen/printer/testdata/function
* Print array comprehensions
* Handle printing anonymous functions
=> Print array comp

ksonnet-gen/printer/printer.go, ksonnet-gen/printer/testdata/upstream/object_comp_binary.jsonnet, ksonnet-gen/printer/testdata/upstream/object_comp_local.jsonnet
Fixes two items:
* Field expressions shouldn't assume they are object comps
* Field expressions can contain binary objects
Fixes #143 
Fixes #142
=> Field expression printing

ksonnet-gen/printer/printer.go, ksonnet-gen/printer/printer_test.go
Special care is given to avoid double-escaping and support mixed-escaped input.
Signed-off-by: Oren Shomron <shomron@gmail.com>
=> Rework stringQuote to behave closer to `jsonnet fmt`
